### PR TITLE
HSK Level Slider

### PR DESCRIPTION
**Pull request by jmingtan**
Reference: https://assembly.com/kanshu/bounties/159

### CODE REVIEW

**Comment by clairetang6** [comment]
@jmingtan This looks great, and it is very close to being done. 

It would be better if the slider updated as it was being dragged, but that will probably be a problem that is solved for us by the angular-material team in the near future. I don't think we need to do anything more immediately. 

The "HSK level" text is a bit hard to read with the transparent background. I think a good solution would be to just have the background behind the text be white. cc: @fernandobuzi . 

And one final tiny detail. The slider needs a little right margin. When the circle is at the last step, it is a little close to the right edge. 

Good job!

**Comment by clairetang6** [comment]
@jmingtan One more thing, the slider should also affect the inline definitions, so that the definitions are hidden in the same way as the pinyin.

**Comment by jmingtan** [comment]
@myfavecolorisgreen I made the changes as requested, however I think hiding the inline definitions leaves some large gaps in the article, as shown in my screenshot.

screen shot 2015-04-06 at 9 48 34 pm

I made it so that when the slider is at maximum (hiding everything), it will remove the inline definitions instead, although this results in a reflow I think it looks cleaner. Let me know what you think!

**Comment by clairetang6** [comment]
@jmingtan Looks good, and I think you're right that it does look cleaner. We may want to hook that up with the toggle button used for hiding/showing definitions, so that when you reach the highest level, it turns the toggle button to off and disables it until you move the slider back down. 

We also will need to make it so that the slider doesn't cover the image when the window viewport height is very small.

If you're interested, I can tag you in upcoming bounties. It was great working with you!

**Comment by jmingtan** [comment]
Thanks @myfavecolorisgreen, it was my pleasure! Sure, do keep me informed if there is anything I can do!

**Pull request merged**
