### PR TITLE
Bounty 144: Skeleton of the Log In Dialog

### PR DESCRIPTION
**Pull request by agrison**
Working on bounty 144 (see https://assembly.com/kanshu/bounties/144).

### CODE REVIEW

**Comment by clairetang6** [comment]
@agrison This looks great so far. The gradient in the background is spot-on. It's just missing a few more things before I can merge it. 
1. There should be another button under the Login button in the dialog. This is in the mockup, "Not registered? <md-button> Create account. </md-button>". Clicking this button should take a user to the sign up dialog, but don't worry about that for this bounty. 
2. Password field should get a type="password" attribute, so that the password is shown in plain text. 
3. Add a little more space on the top and bottom of the icon. Also, a min-width of ~80px should be added so the logo is not too small on smaller screens. 
4. The Login button in the dialog should be disabled if either of the input fields are empty.
5. BONUS (I'll bring the value of the bounty up to 4,000 coins). Clicking the login button should try to log in the user without closing the dialog, so that if a user has entered the wrong password, they can be notified in the same place. The dialog should close either when the user clicks off or if the login has been successful.

**Comment by agrison** [comment]
all done :wink:

**Comment by clairetang6** [comment]
Awesome job @agrison! Merged.

**Comment by clairetang6** [comment]
@fernandobuzi One thing we might want to consider is moving the "Not registered? Create account" into the body of the dialog. In order to have the text show up, @agrison had to darken the background. It might look better if the link were inside dialog. 

image

**Comment by fernandobuzi** [comment]
That's OK @myfavecolorisgreen. We could maybe put it under the password field, like this:

login

Ps: our 'login' doesn't seem aligned to the right with the 'email' and 'password' fields.

**Comment by clairetang6** [comment]
image

@fernandobuzi  This is what the button looks like when it's not disabled. I just checked the angular-material source and the difference in padding between the "content" and "action" of the dialog is there. We can override them if you'd like.

**Comment by fernandobuzi** [comment]
:+1: :) No, let's just leave it like that.

**Pull request merged**
