### PR TITLE
Sign up

### PR DESCRIPTION
**Pull request by alexmreis**
Bounty 132: [Web] Skeleton of the sign up form

I've gone ahead and implemented the sign up form much in the spirit of the existing log in form. I didn't add any links to it, but the login form links to it just fine. 

I've taken the opportunity to also get rid of all jslint warnings and to upgrade angular-material 0.8.3 as 0.7.1 didn't have md-select in it, which I needed for the reading ability dropdown.

Here's the final product:
Sign up screenshot

I hope it's what you expected it to be, it's my first time contributing to an assembly project ^.^

### CODE REVIEW

**Comment by fernandobuzi** [comment]
Cool! :+1: @myfavecolorisgreen will go through it. ;)

**Comment by clairetang6** [comment]
Great job @alexmreis! Thank you for updating our material dependency, and thank you for helping out with cleaning up the js! I have a couple of comments for you on the sign up dialog. 
1. The "Sign up" button should not be uppercase to keep the look consistent with the "Login" button. The sign up button should also have styling to reflect when it's disabled. This should be easy to do if you refactor a little so that the css styles can be shared between the login and signup dialogs. 
2. Clicking the sign up button should log the data to the console. The email, username, password, and language level should be passed by the signup function. 
3. Closing the dialog should reroute the app to /articles. 

After you address these three comments, we can merge your code.

Also, there are some problems when the viewport is made smaller. The dialog is not scrollable, and some parts may be hidden (the link to the login form). Because we are primarily aiming this towards larger screens, we can come back to this issue later, but just something I wanted to bring up now.

**Comment by alexmreis** [comment]
I think I addressed everything in your comments @myfavecolorisgreen , I personally don't think a dialog is the best "pattern" to use if you're aiming smaller screens (i.e. mobile devices), I'd just go for a regular sign up page, so that it scrolls properly and all, but that's me. Can you please have a look?

**Comment by clairetang6** [comment]
@alexmreis Yes, I agree with you that using a dialog doesn't make much sense on a mobile screen. Designing and implementing login and signup forms for mobile can be done in later bounties. 

I also added another redirect when the signup dialog doesn't get completed and array syntax so that the code is minification safe.

**Comment by alexmreis** [comment]
AFAIK ngAnnotate adds the inject arrays itself, so you don't have to. Back
in the days (oh so late 2014) of ngmin you had to, but not anymore.

**Comment by clairetang6** [comment]
@alexmreis Oh, I see. Thanks for letting me know. I have some reading to do..

**Pull request merged**
